{
	"Service": "/ImageHandlingApp/Services/SampleServiceV2.service",
	"DefiningRequests": [{
		"Name": "{ProductId}",
		"Query": "{@odata.readLink}",
		"AutomaticallyRetrievesStreams": true
	}],
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "downloadOfflineMedia"
	},
	"OnSuccess": "/ImageHandlingApp/Actions/Products/DownloadProductImage.action",
	"OnFailure": "/ImageHandlingApp/Actions/Service/DownloadOfflineMediaFailureMessage.action"
}