{
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	 "OnSuccess": "/ImageHandlingApp/Rules/ErrorArchive_CheckForSyncError.js",
	"OnFailure": "/ImageHandlingApp/Actions/Service/SyncFailureMessage.action",
	"Service": "/ImageHandlingApp/Services/Sample.service",
	"DefiningRequests": [
		{
			"Name": "Products",
			"Query": "Products",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "Suppliers",
			"Query": "Suppliers",
			"AutomaticallyRetrievesStreams": false
		}
	]
}