{
	"Service": "/ImageHandlingApp/Services/SampleServiceV2.service",
	"DefiningRequests": [{
		"Name": "Products",
		"Query": "Products",
		"AutomaticallyRetrievesStreams": false
	}],
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/ImageHandlingApp/Actions/Service/SyncFailureMessage.action"
}