{
	"Service": "/ImageHandlingApp/Services/Sample.service",
	"DefiningRequests": [
		{
			"Name": "Products",
			"Query": "Products",
			"AutomaticallyRetrievesStreams": false
		},
		{
			"Name": "Suppliers",
			"Query": "Suppliers",
			"AutomaticallyRetrievesStreams": false
		}
	],
	"_Type": "Action.Type.OfflineOData.Initialize",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Downloading...",
	"ActionResult": {
		"_Name": "init"
	},
	"OnSuccess": "/ImageHandlingApp/Actions/Service/InitializeOfflineSuccessMessage.action",
	"OnFailure": "/ImageHandlingApp/Actions/Service/InitializeOfflineFailureMessage.action"
} 