{
	"OnFailure": "/ProductListApp/Actions/Products/ProductImageDownloadFailure.action",
	"Target": {
		"EntitySet": "Products",
		"Service": "/ProductListApp/Services/SampleServiceV2.service"
	},
	"_Type": "Action.Type.ODataService.DownloadMedia"
}