{
	"OnSuccess": "/ImageHandlingApp/Rules/Product/DocumentFileSave.js",
	"OnFailure": "/ImageHandlingApp/Actions/Products/DownloadMediaFailedToast.action",
	"Target": {
		"EntitySet": "Products",
		"ReadLink": "{@odata.readLink}",
		"Service": "/ImageHandlingApp/Services/SampleServiceV2.service"
	},
	"ActionResult": {
		"_Name": "DownloadImageRes"
	},
	"_Type": "Action.Type.ODataService.DownloadMedia"
}