{
    "_Type": "Action.Type.OfflineOData.Close",
    "Service": "/Devtoberfest/Services/SampleServiceV4.service",
    "Force": true,
    "ActionResult": {
        "_Name": "close"
    },
    "OnSuccess": "/Devtoberfest/Actions/SampleServiceV4/Service/CloseOfflineSuccessMessage.action",
    "OnFailure": "/Devtoberfest/Actions/SampleServiceV4/Service/CloseOfflineFailureMessage.action"
}