{
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/PartialUpload/Actions/UpdateEntityFailureMessage.action",
	"OnSuccess": "/PartialUpload/Actions/UpdateEntitySuccessMessage.action",
	"Properties": {
		"City": "#Control:City/#Value",
		"Country": "#Control:Country/#Value",
		"DateOfBirth": "#Control:DateOfBirth/#Value",
		"EmailAddress": "#Control:EmailAddress/#Value",
		"FirstName": "#Control:FirstName/#Value",
		"HouseNumber": "#Control:HouseNumber/#Value",
		"LastName": "#Control:LastName/#Value",
		"PhoneNumber": "#Control:PhoneNumber/#Value",
		"PostalCode": "#Control:PostalCode/#Value",
		"Street": "#Control:Street/#Value"
	},
	"RequestOptions": {
		"UploadCategory": "Customer"
	},
	"Target": {
		"EntitySet": "Customers",
		"ReadLink": "{@odata.readLink}",
		"Service": "/PartialUpload/Services/Sample.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}