{
	"ActionResult": {
		"_Name": "update"
	},
	"OnFailure": "/PartialUpload/Actions/UpdateEntityFailureMessage.action",
	"OnSuccess": "/PartialUpload/Actions/UpdateEntitySuccessMessage.action",
	"Properties": {
		"CategoryName": "",
		"CurrencyCode": "#Control:CurrencyCode/#Value",
		"DimensionDepth": "#Control:DimensionDepth/#Value",
		"DimensionHeight": "#Control:DimensionHeight/#Value",
		"DimensionUnit": "#Control:DimensionUnit/#Value",
		"DimensionWidth": "#Control:DimensionWidth/#Value",
		"LongDescription": "#Control:LongDescription/#Value",
		"Name": "#Control:Name/#Value",
		"Price": "#Control:Price/#Value",
		"QuantityUnit": "#Control:QuantityUnit/#Value",
		"ShortDescription": "#Control:ShortDescription/#Value",
		"Weight": "#Control:Weight/#Value",
		"WeightUnit": "#Control:WeightUnit/#Value"
	},
	"RequestOptions": {
		"UploadCategory": "Product"
	},
	"Target": {
		"EntitySet": "Products",
		"ReadLink": "{@odata.readLink}",
		"Service": "/PartialUpload/Services/Sample.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}