{
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/PartialUpload/Actions/Service/SyncFailureMessage.action",
	"OnSuccess": "/PartialUpload/Actions/Service/SyncSuccessMessage.action",
	"Service": "/PartialUpload/Services/Sample.service",
	"UploadCategories": [
		"Product"
	],
	"_Type": "Action.Type.OfflineOData.Upload"
}