{
    "Service": "/PersistentFilters/Services/SampleServiceV2.service",
    "DefiningRequests": [{
            "Name": "Customers",
            "Query": "Customers"
        },
        {
            "Name": "Products",
            "Query": "Products",
            "AutomaticallyRetrievesStreams": true
        }
    ],
    "_Type": "Action.Type.OfflineOData.Download",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnFailure": "/PersistentFilters/Actions/Service/SyncFailureMessage.action"
}