{
	"_Type": "Action.Type.ODataService.DownloadStream",
	"ActionResult": {
		"_Name": "DownloadProductStream"
	},
	"Target": {
		"Service": "/MDKDemoApp/Services/Sample.service",
		"EntitySet": "Products",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": [
		"Picture"
	],
	"OnFailure": {
		"Name": "/MDKDemoApp/Actions/GenericBannerMessage.action",
		"Properties": {
			"Animated": true,
			"Duration": 0,
			"Message": "$(L,'product_image_download_failure') - {#ActionResults:download/error}"
		}
	}
}