{
	"Message": "Upload in progress...",
	"CompletionMessage": "Upload Successful",
	"CompletionTimeout": 7,
	"OnSuccess": "/ProductListApp/Actions/Service/UploadOffline.action",
	"OnFailure": "/ProductListApp/Actions/Service/SyncFailureMessage.action",
	"_Type": "Action.Type.ProgressBanner"
}