{
    "ParentLink": {
        "Property": "Items",
        "Target": {
            "EntitySet": "PurchaseOrderHeaders",
            "ReadLink": "{@odata.readLink}"
        }
    },
    "OnFailure": "/Devtoberfest/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/Devtoberfest/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "CurrencyCode": "#Page:PurchaseOrderHeaders_CreatePurchaseOrderItem/#Control:CurrencyCode/#Value",
        "GrossAmount": "#Page:PurchaseOrderHeaders_CreatePurchaseOrderItem/#Control:GrossAmount/#Value",
        "ItemNumber": "#Page:PurchaseOrderHeaders_CreatePurchaseOrderItem/#Control:ItemNumber/#Value",
        "NetAmount": "#Page:PurchaseOrderHeaders_CreatePurchaseOrderItem/#Control:NetAmount/#Value",
        "ProductID": "#Page:PurchaseOrderHeaders_CreatePurchaseOrderItem/#Control:ProductID/#SelectedValue",
        "PurchaseOrderID": "#Page:PurchaseOrderHeaders_CreatePurchaseOrderItem/#Control:PurchaseOrderID/#SelectedValue",
        "Quantity": "#Page:PurchaseOrderHeaders_CreatePurchaseOrderItem/#Control:Quantity/#Value",
        "QuantityUnit": "#Page:PurchaseOrderHeaders_CreatePurchaseOrderItem/#Control:QuantityUnit/#Value",
        "TaxAmount": "#Page:PurchaseOrderHeaders_CreatePurchaseOrderItem/#Control:TaxAmount/#Value"
    },
    "Target": {
        "EntitySet": "PurchaseOrderItems",
        "Service": "/Devtoberfest/Services/SampleServiceV4.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateRelatedEntity"
}