{
	"ActionResult": {
		"_Name": "UploadLog"
	},
	"ActivityIndicatorText": "Uploading...",
	"OnFailure": "/MDKDemoApp/Actions/Logging/LogUploadFailure.action",
	"OnSuccess": "/MDKDemoApp/Actions/Logging/LogUploadSuccessful.action",
	"ShowActivityIndicator": false,
	"_Type": "Action.Type.Logger.Upload"
}