{
	"Animated": true,
	"CompletionMessage": "$(L,'log_upload_success_msg')",
	"CompletionTimeout": 2,
	"Message": "$(L,'log_uploading')",
	"OnSuccess": "/MDKDemoApp/Actions/Logging/UploadLog.action",
	"_Type": "Action.Type.ProgressBanner"
}