{
	"_Type": "Action.Type.Navigation",
	"ActionResult": {
		"_Name": "GenericNavigation"
	},
	"PageToOpen": "/SiblingNavigationApp/Pages/com_sap_edm_sampleservice_v4_SalesOrderHeaders/SalesOrderHeaders_List.page"
}