{
	"Service": "/CalendarControl/Services/Sample.service",
	"DefiningRequests": [
	{
		"Name": "SalesOrderHeaders",
		"Query": "SalesOrderHeaders"
	}
],
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/CalendarControl/Actions/Service/SyncFailureMessage.action"
}