{
	"Service": "/PartialUpload/Services/Sample.service",
	"DefiningRequests": [
	{
		"Name": "Customers",
		"Query": "Customers"
	},
	{
		"Name": "Products",
		"Query": "Products"
	}
],
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/PartialUpload/Actions/Service/SyncFailureMessage.action"
}