{
    "Message": "Failure closing data service - {#ActionResults:close/error}",
    "NumberOfLines": 1,
    "Duration": 3,
    "Animated": true,
    "IsIconHidden": true,
    "_Type": "Action.Type.ToastMessage"
}