{
	"Message": "Download in progress...",
	"CompletionMessage": "Download Successful",
	"CompletionTimeout": 7,
	"OnSuccess": "/MultiSelectContextMenuApp/Actions/Service/DownloadOffline.action",
	"_Type": "Action.Type.ProgressBanner"
}