{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/Devtoberfest/Pages/SampleServiceV4_PurchaseOrderItems/PurchaseOrderItems_Edit.page",
    "_Type": "Action.Type.Navigation"
}