{
	"_Type": "Action.Type.ODataService.Create",
	"Service": "/PDFGeneratorApp/Services/SampleService.service",
	"OnSuccess": "/PDFGeneratorApp/Actions/Service/OpenService.action",
	"OnFailure": "/PDFGeneratorApp/Actions/Service/CreateOpenServiceFailureMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Initializing Application...",
	"ActionResult": {
		"_Name": "init"
	}
}