{
	"Animated": true,
	"CompletionTimeout": 3,
	"Message": "$(L,'checking_for_updates')",
	"OnSuccess": "/MDKDemoApp/Actions/Application/AppUpdateCheck.action",
	"_Type": "Action.Type.ProgressBanner"
}