{
	"ActionResult": {
		"_Name": "AppUpdate"
	},
	"OnFailure": {
		"Name": "/MDKDemoApp/Actions/GenericBannerMessage.action",
		"Properties": {
			"Animated": true,
			"Duration": 0,
			"Message": "$(L,'app_update_failure') {#ActionResults:AppUpdate/error}"
		}
	},
	"OnSuccess": "/MDKDemoApp/Rules/Application/AppUpdateResult.js",
	"_Type": "Action.Type.ApplicationUpdate"
}