{
	"PopoverItems": [
		{
			"Enabled": true,
			"Icon": "sap-icon://synchronize",
			"OnPress": "/MDKDemoApp/Actions/Service/StartSync.action",
			"Title": "$(L,'user_menu_sync')",
			"Visible": "$(PLT,true,true,false)"
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://headset",
			"OnPress": "/MDKDemoApp/Actions/Application/NavToSupport.action",
			"Title": "$(L,'user_menu_support')",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://refresh",
			"OnPress": "/MDKDemoApp/Actions/Application/AppUpdateProgressBanner.action",
			"Title": "$(L,'user_menu_update_check')",
			"Visible": "$(PLT,true,true,false)"
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://hint",
			"OnPress": "/MDKDemoApp/Actions/Application/NavToAbout.action",
			"Title": "$(L,'user_menu_about')",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://log",
			"OnPress": "/MDKDemoApp/Actions/LogoutConfirmation.action",
			"Title": "$(L,'user_menu_logout')",
			"Visible": true
		}
	],
	"_Type": "Action.Type.PopoverMenu"
}