{
	"PopoverItems": [
		{
			"Enabled": true,
			"Icon": "sap-icon://synchronize",
			"OnPress": "/MDKDemoApp/Actions/Service/StartSync.action",
			"Title": "Sync Changes",
			"Visible": "$(PLT,true,true,false)"
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://headset",
			"OnPress": "/MDKDemoApp/Actions/Application/NavToSupport.action",
			"Title": "Support",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://refresh",
			"OnPress": "/MDKDemoApp/Actions/Application/AppUpdateProgressBanner.action",
			"Title": "Check for Updates",
			"Visible": "$(PLT,true,true,false)"
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://hint",
			"OnPress": "/MDKDemoApp/Actions/Application/NavToAbout.action",
			"Title": "About",
			"Visible": true
		},
		{
			"Enabled": true,
			"Icon": "sap-icon://log",
			"OnPress": "/MDKDemoApp/Actions/LogoutConfirmation.action",
			"Title": "Logout",
			"Visible": true
		}
	],
	"_Type": "Action.Type.PopoverMenu"
}