{
	"CancelCaption": "$(L,'reset_cancel')",
	"Message": "$(L,'reset_confirmation')",
	"OKCaption": "$(L,'reset_ok')",
	"OnOK": "/MDKDemoApp/Rules/Application/ResetAppSettingsAndLogout.js",
	"Title": "$(L,'reset_title')",
	"_Type": "Action.Type.Message"
}