{
	"_Type": "Action.Type.ODataService.DeleteEntity",
	"Target": {
		"Service": "/MultiSelectContextMenuApp/Services/Sample.service",
		"EntitySet": "SalesOrderHeaders",
		"ReadLink": "{@odata.readLink}"
	}
}