{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"Properties": {
		"LifeCycleStatus": "?"
	},
	"OnFailure": {
		"Name": "/MultiSelectContextMenuApp/Actions/GenericToastMessage.action",
		"Properties": {
			"Message": "Update Failed: {#ActionResults:UpdateSalesOrderResult/error}",
			"NumberOfLines": 4
		}
	},
	"ActionResult": {
		"_Name": "UpdateSalesOrderResult"
	},
	"Target": {
		"Service": "/MultiSelectContextMenuApp/Services/Sample.service",
		"EntitySet": "SalesOrderHeaders",
		"ReadLink": "{@odata.readLink}"
	}
}