{
	"_Type": "Action.Type.ODataService.Initialize",
	"ActionResult": {
		"_Name": "initialize"
	},
	"OnFailure": {
		"Name": "/MDKDemoApp/Actions/GenericBannerMessage.action",
		"Properties": {
			"Duration": 0,
			"Message": "Failed to Initialize Service - {#ActionResults:initialize/#Property:error}"
		}
	},
	"OnSuccess": "/MDKDemoApp/Actions/Service/InitializeSuccessMessage.action",
	"ShowActivityIndicator": true,
	"ActivityIndicatorText": "Initializing Application...",
	"Service": "/MDKDemoApp/Services/Sample.service",
	"DefiningRequests": [
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "Customers",
			"Query": "Customers"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "ProductCategories",
			"Query": "ProductCategories"
		},
		{
			"AutomaticallyRetrievesStreams": true,
			"Name": "Products",
			"Query": "Products"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "ProductTexts",
			"Query": "ProductTexts"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "SalesOrderHeaders",
			"Query": "SalesOrderHeaders"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "SalesOrderItems",
			"Query": "SalesOrderItems"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "Stock",
			"Query": "Stock"
		},
		{
			"AutomaticallyRetrievesStreams": false,
			"Name": "Suppliers",
			"Query": "Suppliers"
		}
	]
}