{
	"ActionResult": {
		"_Name": "upload"
	},
	"OnFailure": {
		"Name": "/MDKDemoApp/Actions/GenericBannerMessage.action",
		"Properties": {
			"Message": "$(L,'upload_failure_msg',{#ActionResults:upload/#Property:error})"
		}
	},
	"OnSuccess": "/MDKDemoApp/Actions/Service/DownloadProgress.action",
	"Service": "/MDKDemoApp/Services/Sample.service",
	"_Type": "Action.Type.OfflineOData.Upload"
}