{
	"ActionResult": {
		"_Name": "download"
	},
	"OnFailure": {
		"Name": "/MDKDemoApp/Actions/GenericBannerMessage.action",
		"Properties": {
			"Duration": 0,
			"Message": "$(L,'download_failure_msg',{#ActionResults:download/#Property:error})"
		}
	},
	"Service": "/MDKDemoApp/Services/Sample.service",
	"_Type": "Action.Type.OfflineOData.Download"
}