{
	"Animated": true,
	"CompletionMessage": "$(L,'sync_complete')",
	"CompletionTimeout": 3,
	"Message": "$(L,'upload_in_progress')",
	"OnSuccess": "/MDKDemoApp/Actions/Service/OfflineUpload.action",
	"_Type": "Action.Type.ProgressBanner"
}