{
	"Animated": true,
	"CompletionMessage": "Sync Complete",
	"CompletionTimeout": 3,
	"Message": "Upload in Process...",
	"OnSuccess": "/MDKDemoApp/Actions/Service/OfflineUpload.action",
	"_Type": "Action.Type.ProgressBanner"
}