{
	"_Type": "Action.Type.ODataService.Create",
  "Service": "/ProductListApp/Services/SampleServiceV2.service",
  "OnSuccess": "/ProductListApp/Actions/OnlineService/OpenService.action",
  "OnFailure": "/ProductListApp/Actions/OnlineService/CreateServiceFailureToast.action"
}