{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/Devtoberfest/Pages/SampleServiceV4_Products/Products_CreatePurchaseOrderItem.page",
    "_Type": "Action.Type.Navigation"
}