{
	"_Type": "Action.Type.ODataService.Initialize",
	"ActionResult": {
		"_Name": "init"
	},
	"OnFailure": "/HomeScreenWidgetApp/Actions/Service/InitializeOnlineFailureMessage.action",
	"OnSuccess": "/HomeScreenWidgetApp/Actions/Service/InitializeOnlineSuccessMessage.action",
	"ShowActivityIndicator": true,
	"Service": "/HomeScreenWidgetApp/Services/com_sap_edm_sampleservice_v4.service"
}