{
	"Service": "/PrintingSampleApp/Services/SampleService.service",
	"_Type": "Action.Type.ODataService.Open",
	"OnSuccess": "/PrintingSampleApp/Actions/Service/CreateOpenServiceSuccessMessage.action",
	"OnFailure": "/PrintingSampleApp/Actions/Service/CreateOpenServiceFailureMessage.action",
	"ActionResult": {
		"_Name": "init"
	}
}