{
	"_Type": "Action.Type.ToastMessage",
	"OnSuccess": "/HomeScreenWidgetApp/Rules/Widget/RefreshWidgetData.js",
	"Message": "Changed status successfully",
	"NumberOfLines": 2,
	"Duration": 2,
	"IsIconHidden": true,
	"Animated": true
}