{
    "_Type": "Action.Type.Message",
    "Message": "This action will remove all data and return to the Welcome screen. Any local data will be lost. Are you sure you want to continue?",
    "Title": "Reset",
    "OKCaption": "Yes",
    "OnOK": "/VideoPlayerViewExtensionApp/Rules/Application/ResetAppSettingsAndLogout.js",
    "CancelCaption": "No"
}